from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OpenGameText(object):
    def setupUi(self,OpenGameText):
        OpenGameText.setObjectName("OpenGameText")
        OpenGameText.resize(600, 600)
        OpenGameText.setStyleSheet("background-color: rgb(135,206,250);")
        self.push_start_time = QtWidgets.QPushButton(OpenGameText)
        self.push_start_time.setGeometry(QtCore.QRect(180,20,230,50))
        self.push_start_time.setText("Start Time")
        self.push_start_time.setObjectName("push_start_time")
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.push_start_time.setFont(font)

        self.push_exit = QtWidgets.QPushButton(OpenGameText)
        self.push_exit.setText("EXIT")
        self.push_exit.setGeometry(QtCore.QRect(10,10,120,50))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.push_exit.setFont(font)

        self.push_next = QtWidgets.QPushButton(OpenGameText)
        self.push_next.setText("Next")
        self.push_next.setGeometry(QtCore.QRect(450,540,130,50))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.push_next.setFont(font)

        self.push_reset = QtWidgets.QPushButton(OpenGameText)
        self.push_reset.setText("Reset")
        self.push_reset.setGeometry(QtCore.QRect(10,540,130,50))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.push_reset.setFont(font)

        self.push_start_team_two = QtWidgets.QPushButton(OpenGameText)
        self.push_start_team_two.setText("Start Team2")
        self.push_start_team_two.setGeometry(QtCore.QRect(200,540,170,50))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.push_start_team_two.setFont(font)



        self.push_second = QtWidgets.QLineEdit(OpenGameText)
        self.push_second.setGeometry(QtCore.QRect(450, 10, 127, 50))
        font = QtGui.QFont()
        font.setPixelSize(20)
        font.setBold(True)
        self.push_second.setText("    00:00:00")
        self.push_second.setFont(font)
        self.push_second.maxLength()
        self.push_second.alignment()
        self.push_second.setReadOnly(True)
        self.push_second.setStyleSheet("background-color: rgb(240,255,255)")

        self.verticalLayoutWidget = QtWidgets.QWidget(OpenGameText)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50,80,480,450))
        #self.verticalLayoutWidget.setStyleSheet("background-color: rgb(0,0,0)")
        self.verticalLayoutWidget.setObjectName("toxna vortec text piti lini")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.btn_text1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_text1.setText("hello")
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text1.setFont(font)
        self.btn_text1.setObjectName("btn_text1")
        self.verticalLayout.addWidget(self.btn_text1)

        self.btn_text2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_text2.setText("barev")
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text2.setFont(font)
        self.btn_text2.setObjectName("btn_text2")
        self.verticalLayout.addWidget(self.btn_text2)

        self.btn_text3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_text3.setText("man")
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text3.setFont(font)
        self.btn_text3.setObjectName("btn_text3")
        self.verticalLayout.addWidget(self.btn_text3)

        self.btn_text4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_text4.setText("are you okey")
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text4.setFont(font)
        self.btn_text4.setObjectName("btn_text4")
        self.verticalLayout.addWidget(self.btn_text4)

        self.btn_text5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_text5.setText("axpers")
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text5.setFont(font)
        self.btn_text5.setObjectName("btn_text5")
        self.verticalLayout.addWidget(self.btn_text5)

        self.btn_text6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_text6.setText("davay")
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text6.setFont(font)
        self.btn_text6.setObjectName("btn_text6")
        self.verticalLayout.addWidget(self.btn_text6)

        self.btn_text7 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_text7.setText("lav txa es du")
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text7.setFont(font)
        self.btn_text7.setObjectName("btn_text7")
        self.verticalLayout.addWidget(self.btn_text7)

        self.btn_text8 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_text8.setText("okey")
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text8.setFont(font)
        self.btn_text8.setObjectName("btn_text8")
        self.verticalLayout.addWidget(self.btn_text8)

        self.btn_text9 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_text9.setText("kinoya")
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text9.setFont(font)
        self.btn_text9.setObjectName("btn_text9")
        self.verticalLayout.addWidget(self.btn_text9)

        self.btn_text10 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_text10.setText("esim")
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text10.setFont(font)
        self.btn_text10.setObjectName("btn_text10")
        self.verticalLayout.addWidget(self.btn_text10)

        self.btn_text11 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_text11.setText("chgitem")
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text11.setFont(font)
        self.btn_text11.setObjectName("btn_text11")
        self.verticalLayout.addWidget(self.btn_text11)

        self.btn_text12 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_text12.setText("karoxa")
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text12.setFont(font)
        self.btn_text12.setObjectName("btn_text12")
        self.verticalLayout.addWidget(self.btn_text12)

        self.retranslateUi(OpenGameText)
        QtCore.QMetaObject.connectSlotsByName(OpenGameText)

    def retranslateUi(self, OpenGameText):
        _translate = QtCore.QCoreApplication.translate
        OpenGameText.setWindowTitle(_translate("ArmenianGuessTheWord", "ArmenianGuessTheWord"))
